### ISSUE TITLE
Move to types/npm-sequelize

### ISSUE THREAD

**Issue by felixfbecker** [types/typed-sequelize#39]
I think such an important typing should be under types/. Moving a repo is pretty painless with GitHub.

**Comment by felixfbecker** [comment]
@louy ?

**Comment by felixfbecker** [comment]
@louy it's been over a month now since I heard from you - I think so these typings can evolve and be maintained it would be best to move them to the types org. It would be nice if you could move the repo or give me admin rights to do it, otherwise I will just fork the repo (which wouldn't be as nice because then we have two repos floating around).

**Comment by alitaheri** [comment]
@felixfbecker I think with the `@types 2.0` we should stick to DT anyway.

**Comment by felixfbecker** [comment]
@alitaheri no. DT is a giant unmanageable monorepo. TS team is planning redirections from DT to other repos (by a JSON file or git submodule)

**Comment by louy** [comment]
Sorry it took a while. I've been really busy recently.

**Comment by JD-Robbs** [comment]
When pulling `npm i --save @types/sequelize` it says it's for v4.0.39, but the actual typing files are for v3.

I am just migrating from `typings` to using `@types` - but don't seem to be able to install your typings that way.

Just FYI in case you think it's working.

**Comment by felixfbecker** [comment]
@JD-Robbs these typings are not the ones you get when you `npm i -S @types/sequelize`. See https://github.com/Microsoft/types-publisher/issues/4

**Comment by JD-Robbs** [comment]
@felixfbecker Aha! Well, that would explain it - thanks for the reference and glad to see they're working on a feature for publishing different versions.

I'll stick with `typings` in the meantime.
